# Generated by Django 3.1 on 2020-05-31 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aspecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Division_Territorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('plaza', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Oper', 'Operaciones'), ('Admon', 'Administración'), ('Serv', 'Servicios'), ('Tecn', 'Técnicos'), ('Func', 'Funcionario')], max_length=255)),
                ('subordinados', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('evaluar', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=255)),
                ('anexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Anexo')),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Centro')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Trabajador')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('peso', models.IntegerField()),
                ('valoracion', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=255)),
                ('aspecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Aspecto')),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='division_territorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Division_Territorial'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='aspecto',
            field=models.ManyToManyField(blank=True, to='directorio.Aspecto'),
        ),
    ]
