# Generated by Django 3.1 on 2020-06-01 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_cumplimiento', models.DateField()),
                ('estado', models.CharField(choices=[('cumplido', 'Cumplido'), ('incumplido-imputable', 'Incumplido Imputable'), ('incumplido-no-imputable', 'Incumplido no Imputable')], max_length=255)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('evidencia', models.TextField()),
                ('fecha', models.DateField()),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Formacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_cumplimiento', models.DateField()),
                ('estado', models.CharField(choices=[('cumplido', 'Cumplido'), ('incumplido-imputable', 'Incumplido Imputable'), ('incumplido-no-imputable', 'Incumplido no Imputable')], max_length=255)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Logros_Fortaleza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('muy-bien', 'Muy Bien'), ('bien', 'Bien'), ('regular', 'Regular'), ('mal', 'Mal')], max_length=255)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Deficiencias_Debilidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Criterio_Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('criterio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Criterio')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.Trabajador')),
            ],
        ),
    ]
