# Generated by Django 3.1 on 2020-04-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
