# Generated by Django 3.1 on 2020-04-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('persona', models.ManyToManyField(blank=True, to='directorio.Persona')),
            ],
        ),
    ]
